apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: production
images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: a923fe6c30dd4e601593d0f2692961d936cede36
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: a923fe6c30dd4e601593d0f2692961d936cede36
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: a923fe6c30dd4e601593d0f2692961d936cede36
