apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
- path: broadcaster-patch.yaml
- path: remove-backup-cronjob.yaml

images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: 5d9f3c58d5924ae0d9f1697cad2bc277e83e46e3
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: 5d9f3c58d5924ae0d9f1697cad2bc277e83e46e3
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: 5d9f3c58d5924ae0d9f1697cad2bc277e83e46e3
