apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
- path: broadcaster-patch.yaml
- path: remove-backup-cronjob.yaml

images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: bcaa3aebc29cb0e1eeb72c17751fb1a8b3e4e05a
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: bcaa3aebc29cb0e1eeb72c17751fb1a8b3e4e05a
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: bcaa3aebc29cb0e1eeb72c17751fb1a8b3e4e05a
