apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
- path: broadcaster-patch.yaml
- path: remove-backup-cronjob.yaml

images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: da5ff295bb67a2a8626777f801c1ad87806f1a3d
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: da5ff295bb67a2a8626777f801c1ad87806f1a3d
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: da5ff295bb67a2a8626777f801c1ad87806f1a3d
